import type { WebsiteRecord } from "@/src/types/website-audit";

export const websiteAuditMockRecord: WebsiteRecord = {
    id: "website-001",
    businessName: "Harbourview Dental Studio",
    websiteUrl: "https://harbourviewdental.example",
    businessEmail: "hello@harbourviewdental.example",
    industry: "Dental clinic",
    location: "Toronto, ON",
    source: "Public audit submission",
    internalNotes:
        "Interested in improving local lead conversion and clearer service positioning.",
    websiteStatus: "ready",
    auditStatus: "complete",
    demoStatus: "published",
    outreachStatus: "draft-ready",
    updatedAt: "2026-07-14",
    generatedAt: "2026-07-14",
    overallScore: 78,
    googleMetrics: [
        {
            id: "performance",
            label: "Performance",
            value: 74,
            summary: "Core pages load reasonably well but image payloads still slow mobile visits.",
        },
        {
            id: "accessibility",
            label: "Accessibility",
            value: 81,
            summary: "Most structure is in place, with a few label and contrast improvements needed.",
        },
        {
            id: "best-practices",
            label: "Best practices",
            value: 84,
            summary: "The site follows common standards with a few minor technical cleanup items.",
        },
        {
            id: "seo",
            label: "SEO basics",
            value: 76,
            summary: "Key fundamentals exist, but page targeting and metadata could be sharper.",
        },
    ],
    niceGuyMetrics: [
        {
            id: "messaging",
            label: "Messaging clarity",
            value: 80,
            summary: "The service offering is understandable, though the primary value proposition can be stronger.",
        },
        {
            id: "trust",
            label: "Trust signals",
            value: 73,
            summary: "The site would benefit from more visible reviews, credentials, and team context.",
        },
        {
            id: "mobile",
            label: "Mobile experience",
            value: 77,
            summary: "Layouts adapt well overall, but some sections feel dense on smaller screens.",
        },
        {
            id: "conversion",
            label: "Conversion clarity",
            value: 71,
            summary: "Calls to action are present, but intent paths could be clearer for new visitors.",
        },
    ],
    strengths: [
        {
            id: "strength-1",
            title: "Strong service relevance",
            summary: "Visitors can quickly see the clinic's core services and location coverage.",
            impact: "medium",
            category: "messaging",
        },
        {
            id: "strength-2",
            title: "Consistent contact access",
            summary: "Phone and booking actions remain visible across the main pages.",
            impact: "medium",
            category: "conversion",
        },
    ],
    opportunities: [
        {
            id: "opportunity-1",
            title: "Clarify first-screen value proposition",
            summary: "The homepage should explain who the clinic serves and why booking here feels safe and easy.",
            impact: "high",
            category: "messaging",
        },
        {
            id: "opportunity-2",
            title: "Reduce large media payloads",
            summary: "Compressing hero imagery and reviewing media sizing should improve mobile performance.",
            impact: "high",
            category: "performance",
        },
        {
            id: "opportunity-3",
            title: "Add stronger trust anchors",
            summary: "Reviews, certifications, and before/after proof should appear earlier in the journey.",
            impact: "medium",
            category: "trust",
        },
    ],
    screenshots: [
        "Homepage desktop screenshot placeholder",
        "Homepage mobile screenshot placeholder",
        "Services page screenshot placeholder",
    ],
    methodology: [
        "Automated technical checks review general performance, accessibility, and baseline search readiness.",
        "Google PageSpeed data helps identify loading bottlenecks and field-tested speed issues.",
        "Visual review focuses on messaging, trust signals, mobile clarity, and conversion friction.",
        "Recommendations are prioritized for practical small-business improvements rather than vanity scoring.",
    ],
    demo: {
        id: "demo-001",
        title: "Homepage trust and booking concept",
        description:
            "A focused concept showing clearer positioning, stronger trust cues, and more direct booking paths.",
        status: "published",
        reportToken: "sample-report-token",
        demoToken: "sample-demo-token",
        desktopPreviewLabel: "Desktop homepage demo placeholder",
        mobilePreviewLabel: "Mobile homepage demo placeholder",
    },
};

export const websiteAuditMockRecords: WebsiteRecord[] = [
    websiteAuditMockRecord,
    {
        ...websiteAuditMockRecord,
        id: "website-002",
        businessName: "Northline Legal Services",
        websiteUrl: "https://northlinelegal.example",
        businessEmail: "info@northlinelegal.example",
        industry: "Legal services",
        location: "Mississauga, ON",
        source: "Manual prospect research",
        websiteStatus: "new",
        auditStatus: "queued",
        demoStatus: "planned",
        outreachStatus: "not-contacted",
        updatedAt: "2026-07-15",
        generatedAt: "2026-07-15",
        overallScore: 64,
    },
    {
        ...websiteAuditMockRecord,
        id: "website-003",
        businessName: "Willow & Pine Landscaping",
        websiteUrl: "https://willowpine.example",
        businessEmail: "office@willowpine.example",
        industry: "Landscaping",
        location: "Vaughan, ON",
        source: "Referral",
        websiteStatus: "ready",
        auditStatus: "processing",
        demoStatus: "in-progress",
        outreachStatus: "replied",
        updatedAt: "2026-07-16",
        generatedAt: "2026-07-13",
        overallScore: 82,
    },
];
