import { VI_PATHS } from "./valleyInterlockingConfig";
import {
  VI_BACKYARD_RELATED_SERVICES,
  VI_DRIVEWAY_RELATED_SERVICES,
  VI_INTERLOCKING_RELATED_SERVICES,
  VI_LANDSCAPING_RELATED_SERVICES,
  VI_LAWN_CARE_RELATED_SERVICES,
  VI_LIGHTING_RELATED_SERVICES,
  VI_PATIO_RELATED_SERVICES,
  VI_PERGOLA_RELATED_SERVICES,
  VI_PORCH_RELATED_SERVICES,
  VI_RELATED_SERVICES_BY_PATH,
} from "./valleyInterlockingSiteContent";

export type ViRelatedService = (typeof VI_INTERLOCKING_RELATED_SERVICES)[number];

export {
  VI_BACKYARD_RELATED_SERVICES,
  VI_DRIVEWAY_RELATED_SERVICES,
  VI_INTERLOCKING_RELATED_SERVICES,
  VI_LANDSCAPING_RELATED_SERVICES,
  VI_LAWN_CARE_RELATED_SERVICES,
  VI_LIGHTING_RELATED_SERVICES,
  VI_PATIO_RELATED_SERVICES,
  VI_PERGOLA_RELATED_SERVICES,
  VI_PORCH_RELATED_SERVICES,
  VI_RELATED_SERVICES_BY_PATH,
};

export function getViRelatedServices(pathname: string): readonly ViRelatedService[] {
  const path = pathname.replace(/\/$/, "") || "/";
  return VI_RELATED_SERVICES_BY_PATH[path] ?? [];
}
