import type { ActivityLogType } from "@/src/schemas/enums";

export const ACTIVITY_EVENTS = {
    WEBSITE_CREATED: "website-created",
    WEBSITE_UPDATED: "website-updated",
    WEBSITE_ARCHIVED: "website-archived",
    WEBSITE_RESTORED: "website-restored",
    WEBSITE_DELETED: "website-deleted",

    CRAWL_QUEUED: "crawl-queued",
    CRAWL_STARTED: "crawl-started",
    CRAWL_PAGE_COMPLETED: "crawl-page-completed",
    CRAWL_COMPLETED: "crawl-completed",
    CRAWL_FAILED: "crawl-failed",
    CRAWL_CANCELLED: "crawl-cancelled",
    CRAWL_PARTIAL: "crawl-partial",

    SCREENSHOT_CREATED: "screenshot-created",
    SCREENSHOT_FAILED: "screenshot-failed",
    SCREENSHOT_CAPTURE_STARTED: "screenshot-capture-started",
    SCREENSHOT_CAPTURED: "screenshot-captured",
    SCREENSHOT_CAPTURE_COMPLETED: "screenshot-capture-completed",
    SCREENSHOT_CAPTURE_FAILED: "screenshot-capture-failed",
    SCREENSHOT_DELETED: "screenshot-deleted",

    PAGESPEED_QUEUED: "pagespeed-queued",
    PAGESPEED_STARTED: "pagespeed-started",
    PAGESPEED_MOBILE_COMPLETED: "pagespeed-mobile-completed",
    PAGESPEED_DESKTOP_COMPLETED: "pagespeed-desktop-completed",
    PAGESPEED_MOBILE_FAILED: "pagespeed-mobile-failed",
    PAGESPEED_DESKTOP_FAILED: "pagespeed-desktop-failed",
    PAGESPEED_COMPLETED: "pagespeed-completed",
    PAGESPEED_PARTIAL: "pagespeed-partial",
    PAGESPEED_FAILED: "pagespeed-failed",

    METRICS_QUEUED: "niceguy-queued",
    METRICS_STARTED: "niceguy-started",
    METRICS_COMPLETED: "niceguy-completed",
    METRICS_FAILED: "niceguy-failed",

    AI_ANALYSIS_QUEUED: "ai-analysis-queued",
    AI_ANALYSIS_STARTED: "ai-analysis-started",
    AI_ANALYSIS_COMPLETED: "ai-analysis-completed",
    AI_ANALYSIS_PARTIAL: "ai-analysis-partial",
    AI_ANALYSIS_FAILED: "ai-analysis-failed",
    AI_SUMMARY_COMPLETED: "ai-summary-completed",
    AI_SUMMARY_FAILED: "ai-summary-failed",
    HERO_SUGGESTIONS_COMPLETED: "hero-suggestions-completed",
    HERO_SUGGESTIONS_FAILED: "hero-suggestions-failed",
    HERO_SUGGESTION_SELECTED: "hero-suggestion-selected",
    HERO_SUGGESTION_REJECTED: "hero-suggestion-rejected",
    HERO_SUGGESTION_RESTORED: "hero-suggestion-restored",

    PUBLIC_REPORT_CREATED: "public-report-created",
    PUBLIC_REPORT_UPDATED: "public-report-updated",
    PUBLIC_REPORT_PUBLISHED: "public-report-published",
    PUBLIC_REPORT_UNPUBLISHED: "public-report-unpublished",
    PUBLIC_REPORT_REVISED: "public-report-revised",
    PUBLIC_REPORT_ARCHIVED: "public-report-archived",
    PUBLIC_REPORT_TOKEN_ROTATED: "public-report-token-rotated",
    PUBLIC_REPORT_VIEWED: "public-report-viewed",

    PDF_REPORT_QUEUED: "pdf-report-queued",
    PDF_REPORT_STARTED: "pdf-report-started",
    PDF_REPORT_COMPLETED: "pdf-report-completed",
    PDF_REPORT_FAILED: "pdf-report-failed",
    PDF_REPORT_DOWNLOADED: "pdf-report-downloaded",
    PDF_REPORT_DELETED: "pdf-report-deleted",

    OUTREACH_DRAFT_STARTED: "outreach-draft-started",
    OUTREACH_DRAFT_GENERATED: "outreach-draft-generated",
    OUTREACH_DRAFT_FAILED: "outreach-draft-failed",
    OUTREACH_DRAFT_EDITED: "outreach-draft-edited",
    OUTREACH_DRAFT_APPROVED: "outreach-draft-approved",
    OUTREACH_DRAFT_REJECTED: "outreach-draft-rejected",
    OUTREACH_DRAFT_ARCHIVED: "outreach-draft-archived",
    OUTREACH_DRAFT_COPIED: "outreach-draft-copied",

    DEMO_PROJECT_CREATED: "demo-project-created",
    DEMO_PROJECT_UPDATED: "demo-project-updated",
    DEMO_GENERATION_QUEUED: "demo-generation-queued",
    DEMO_GENERATION_STARTED: "demo-generation-started",
    DEMO_GENERATION_COMPLETED: "demo-generation-completed",
    DEMO_GENERATION_FAILED: "demo-generation-failed",
    DEMO_GENERATION_CANCELLED: "demo-generation-cancelled",
    DEMO_PREVIEW_OPENED: "demo-preview-opened",
    DEMO_APPROVED: "demo-approved",
    DEMO_REJECTED: "demo-rejected",
    DEMO_ARCHIVED: "demo-archived",
    DEMO_ASSET_APPROVED: "demo-asset-approved",
    DEMO_ASSET_REJECTED: "demo-asset-rejected",

    ADMINISTRATOR_NOTE_ADDED: "administrator-note-added",
    ADMINISTRATOR_NOTE_UPDATED: "administrator-note-updated",
    ADMINISTRATOR_NOTE_ARCHIVED: "administrator-note-archived",
    ADMINISTRATOR_ACTION_FAILED: "administrator-action-failed",
} as const;

export type ActivityEventType = ActivityLogType;

export const ACTIVITY_CATEGORIES = [
    "website",
    "crawl",
    "screenshot",
    "pagespeed",
    "metrics",
    "ai",
    "report",
    "pdf",
    "outreach",
    "demo",
    "audit",
    "administrator",
    "system",
] as const;

export type ActivityCategory = (typeof ACTIVITY_CATEGORIES)[number];

export const ACTIVITY_SEVERITIES = ["info", "success", "warning", "error"] as const;

export type ActivitySeverity = (typeof ACTIVITY_SEVERITIES)[number];

export const ACTIVITY_ACTOR_TYPES = [
    "system",
    "administrator",
    "worker",
    "provider",
] as const;

export type ActivityActorType = (typeof ACTIVITY_ACTOR_TYPES)[number];

const EVENT_CATEGORY_MAP: Record<string, ActivityCategory> = {
    "website-created": "website",
    "website-updated": "website",
    "website-archived": "website",
    "website-restored": "website",
    "website-deleted": "website",
    "crawl-queued": "crawl",
    "crawl-started": "crawl",
    "crawl-page-completed": "crawl",
    "crawl-completed": "crawl",
    "crawl-failed": "crawl",
    "crawl-cancelled": "crawl",
    "crawl-partial": "crawl",
    "screenshot-created": "screenshot",
    "screenshot-failed": "screenshot",
    "screenshot-capture-started": "screenshot",
    "screenshot-captured": "screenshot",
    "screenshot-capture-completed": "screenshot",
    "screenshot-capture-failed": "screenshot",
    "screenshot-deleted": "screenshot",
    "pagespeed-queued": "pagespeed",
    "pagespeed-started": "pagespeed",
    "pagespeed-mobile-completed": "pagespeed",
    "pagespeed-desktop-completed": "pagespeed",
    "pagespeed-mobile-failed": "pagespeed",
    "pagespeed-desktop-failed": "pagespeed",
    "pagespeed-completed": "pagespeed",
    "pagespeed-partial": "pagespeed",
    "pagespeed-failed": "pagespeed",
    "niceguy-queued": "metrics",
    "niceguy-started": "metrics",
    "niceguy-completed": "metrics",
    "niceguy-failed": "metrics",
    "ai-analysis-queued": "ai",
    "ai-analysis-started": "ai",
    "ai-analysis-completed": "ai",
    "ai-analysis-partial": "ai",
    "ai-analysis-failed": "ai",
    "ai-summary-completed": "ai",
    "ai-summary-failed": "ai",
    "hero-suggestions-completed": "ai",
    "hero-suggestions-failed": "ai",
    "hero-suggestion-selected": "ai",
    "hero-suggestion-rejected": "ai",
    "hero-suggestion-restored": "ai",
    "ai-analysis-generated": "ai",
    "public-report-created": "report",
    "public-report-updated": "report",
    "public-report-published": "report",
    "public-report-unpublished": "report",
    "public-report-revised": "report",
    "public-report-archived": "report",
    "public-report-token-rotated": "report",
    "public-report-viewed": "report",
    "pdf-report-queued": "pdf",
    "pdf-report-started": "pdf",
    "pdf-report-completed": "pdf",
    "pdf-report-failed": "pdf",
    "pdf-report-downloaded": "pdf",
    "pdf-report-deleted": "pdf",
    "pdf-generated": "pdf",
    "outreach-draft-started": "outreach",
    "outreach-draft-generated": "outreach",
    "outreach-draft-failed": "outreach",
    "outreach-draft-edited": "outreach",
    "outreach-draft-approved": "outreach",
    "outreach-draft-rejected": "outreach",
    "outreach-draft-archived": "outreach",
    "outreach-draft-copied": "outreach",
    "email-generated": "outreach",
    "email-sent": "outreach",
    "demo-project-created": "demo",
    "demo-project-updated": "demo",
    "demo-generation-queued": "demo",
    "demo-generation-started": "demo",
    "demo-generation-completed": "demo",
    "demo-generation-failed": "demo",
    "demo-generation-cancelled": "demo",
    "demo-preview-opened": "demo",
    "demo-approved": "demo",
    "demo-rejected": "demo",
    "demo-archived": "demo",
    "demo-asset-approved": "demo",
    "demo-asset-rejected": "demo",
    "demo-published": "demo",
    "audit-run-created": "audit",
    "audit-run-started": "audit",
    "audit-run-completed": "audit",
    "audit-run-partial": "audit",
    "audit-run-failed": "audit",
    "audit-run-cancelled": "audit",
    "audit-run-finalized": "audit",
    "audit-run-archived": "audit",
    "audit-run-restored": "audit",
    "audit-comparison-opened": "audit",
    "audit-history-migrated": "audit",
    "rate-limit-triggered": "system",
    "provider-rate-limit-triggered": "system",
    "global-budget-warning": "system",
    "global-budget-exhausted": "system",
    "administrator-note-added": "administrator",
    "administrator-note-updated": "administrator",
    "administrator-note-archived": "administrator",
    "administrator-action-failed": "administrator",
};

const EVENT_SEVERITY_MAP: Record<string, ActivitySeverity> = {
    "website-created": "info",
    "website-updated": "info",
    "website-archived": "info",
    "website-restored": "info",
    "website-deleted": "warning",
    "crawl-queued": "info",
    "crawl-started": "info",
    "crawl-page-completed": "info",
    "crawl-completed": "success",
    "crawl-failed": "error",
    "crawl-cancelled": "warning",
    "crawl-partial": "warning",
    "screenshot-created": "success",
    "screenshot-failed": "error",
    "screenshot-capture-started": "info",
    "screenshot-captured": "success",
    "screenshot-capture-completed": "success",
    "screenshot-capture-failed": "error",
    "screenshot-deleted": "warning",
    "pagespeed-queued": "info",
    "pagespeed-started": "info",
    "pagespeed-mobile-completed": "success",
    "pagespeed-desktop-completed": "success",
    "pagespeed-mobile-failed": "error",
    "pagespeed-desktop-failed": "error",
    "pagespeed-completed": "success",
    "pagespeed-partial": "warning",
    "pagespeed-failed": "error",
    "niceguy-queued": "info",
    "niceguy-started": "info",
    "niceguy-completed": "success",
    "niceguy-failed": "error",
    "ai-analysis-queued": "info",
    "ai-analysis-started": "info",
    "ai-analysis-completed": "success",
    "ai-analysis-partial": "warning",
    "ai-analysis-failed": "error",
    "ai-summary-completed": "success",
    "ai-summary-failed": "error",
    "hero-suggestions-completed": "success",
    "hero-suggestions-failed": "error",
    "hero-suggestion-selected": "info",
    "hero-suggestion-rejected": "warning",
    "hero-suggestion-restored": "info",
    "ai-analysis-generated": "success",
    "public-report-created": "info",
    "public-report-updated": "info",
    "public-report-published": "success",
    "public-report-unpublished": "warning",
    "public-report-revised": "info",
    "public-report-archived": "warning",
    "public-report-token-rotated": "info",
    "public-report-viewed": "info",
    "pdf-report-queued": "info",
    "pdf-report-started": "info",
    "pdf-report-completed": "success",
    "pdf-report-failed": "error",
    "pdf-report-downloaded": "info",
    "pdf-report-deleted": "warning",
    "pdf-generated": "success",
    "outreach-draft-started": "info",
    "outreach-draft-generated": "info",
    "outreach-draft-failed": "error",
    "outreach-draft-edited": "info",
    "outreach-draft-approved": "success",
    "outreach-draft-rejected": "warning",
    "outreach-draft-archived": "warning",
    "outreach-draft-copied": "info",
    "email-generated": "info",
    "email-sent": "success",
    "demo-project-created": "info",
    "demo-project-updated": "info",
    "demo-generation-queued": "info",
    "demo-generation-started": "info",
    "demo-generation-completed": "success",
    "demo-generation-failed": "error",
    "demo-generation-cancelled": "warning",
    "demo-preview-opened": "info",
    "demo-approved": "success",
    "demo-rejected": "warning",
    "demo-archived": "warning",
    "demo-asset-approved": "info",
    "demo-asset-rejected": "warning",
    "demo-published": "success",
    "audit-run-created": "info",
    "audit-run-started": "info",
    "audit-run-completed": "success",
    "audit-run-partial": "warning",
    "audit-run-failed": "error",
    "audit-run-cancelled": "warning",
    "audit-run-finalized": "info",
    "audit-run-archived": "warning",
    "audit-run-restored": "info",
    "audit-comparison-opened": "info",
    "audit-history-migrated": "info",
    "rate-limit-triggered": "warning",
    "provider-rate-limit-triggered": "warning",
    "global-budget-warning": "warning",
    "global-budget-exhausted": "error",
    "administrator-note-added": "info",
    "administrator-note-updated": "info",
    "administrator-note-archived": "warning",
    "administrator-action-failed": "error",
};

export function getActivityCategoryForEvent(eventType: string): ActivityCategory {
    return EVENT_CATEGORY_MAP[eventType] ?? "system";
}

export function getActivitySeverityForEvent(eventType: string): ActivitySeverity {
    return EVENT_SEVERITY_MAP[eventType] ?? "info";
}

export const NOTE_EVENT_TYPES = new Set<string>([
    ACTIVITY_EVENTS.ADMINISTRATOR_NOTE_ADDED,
    ACTIVITY_EVENTS.ADMINISTRATOR_NOTE_UPDATED,
    ACTIVITY_EVENTS.ADMINISTRATOR_NOTE_ARCHIVED,
]);

export function isAdministratorNoteEvent(eventType: string): boolean {
    return NOTE_EVENT_TYPES.has(eventType);
}
