/** Demo-only breed lists for the explorer search (North American shelter–style naming). */

export const NEOPETS_DOG_BREEDS = [
  "Affenpinscher",
  "Afghan Hound",
  "Airedale Terrier",
  "Akita",
  "Alaskan Malamute",
  "American Bulldog",
  "American Eskimo Dog",
  "American Staffordshire Terrier",
  "Australian Cattle Dog",
  "Australian Shepherd",
  "Basenji",
  "Basset Hound",
  "Beagle",
  "Belgian Malinois",
  "Bernedoodle",
  "Bernese Mountain Dog",
  "Bichon Frise",
  "Bloodhound",
  "Border Collie",
  "Boston Terrier",
  "Boxer",
  "Boxer Mix",
  "Brittany",
  "Bull Terrier",
  "Bulldog (English)",
  "Cairn Terrier",
  "Cane Corso",
  "Cavalier King Charles Spaniel",
  "Chesapeake Bay Retriever",
  "Chihuahua",
  "Chinese Crested",
  "Chow Chow",
  "Cockapoo",
  "Cocker Spaniel",
  "Collie",
  "Corgi (Cardigan)",
  "Corgi (Pembroke)",
  "Dachshund",
  "Dalmatian",
  "Doberman Pinscher",
  "Dogo Argentino",
  "Dutch Shepherd",
  "English Setter",
  "English Springer Spaniel",
  "French Bulldog",
  "German Shepherd Dog",
  "German Shorthaired Pointer",
  "German Wirehaired Pointer",
  "Giant Schnauzer",
  "Goldendoodle",
  "Golden Retriever",
  "Great Dane",
  "Great Pyrenees",
  "Greater Swiss Mountain Dog",
  "Greyhound",
  "Havanese",
  "Husky (Alaskan)",
  "Husky (Siberian)",
  "Irish Setter",
  "Irish Wolfhound",
  "Italian Greyhound",
  "Jack Russell Terrier",
  "Labradoodle",
  "Labrador Retriever",
  "Lagotto Romagnolo",
  "Lhasa Apso",
  "Maltese",
  "Mastiff",
  "Miniature American Shepherd",
  "Miniature Pinscher",
  "Miniature Schnauzer",
  "Mixed Breed",
  "Newfoundland",
  "Norwegian Elkhound",
  "Nova Scotia Duck Tolling Retriever",
  "Olde English Bulldogge",
  "Papillon",
  "Pit Bull Type",
  "Pointer",
  "Polish Lowland Sheepdog",
  "Pomeranian",
  "Poodle (Miniature)",
  "Poodle (Standard)",
  "Poodle (Toy)",
  "Portuguese Water Dog",
  "Pug",
  "Rhodesian Ridgeback",
  "Rottweiler",
  "Saint Bernard",
  "Samoyed",
  "Schnauzer (Standard)",
  "Scottish Terrier",
  "Shar Pei",
  "Sheepadoodle",
  "Shetland Sheepdog",
  "Shiba Inu",
  "Shih Tzu",
  "Soft Coated Wheaten Terrier",
  "Staffordshire Bull Terrier",
  "Vizsla",
  "Weimaraner",
  "Welsh Terrier",
  "West Highland White Terrier",
  "Whippet",
  "Wire Fox Terrier",
  "Yorkshire Terrier",
].sort((a, b) => a.localeCompare(b));

export const NEOPETS_CAT_BREEDS = [
  "Abyssinian",
  "American Bobtail",
  "American Curl",
  "American Shorthair",
  "American Wirehair",
  "Balinese",
  "Bengal",
  "Birman",
  "Bombay",
  "British Longhair",
  "British Shorthair",
  "Burmese",
  "Burmilla",
  "Chartreux",
  "Chausie",
  "Cornish Rex",
  "Devon Rex",
  "Domestic Longhair",
  "Domestic Mediumhair",
  "Domestic Shorthair",
  "Egyptian Mau",
  "European Shorthair",
  "Exotic Longhair",
  "Exotic Shorthair",
  "Havana Brown",
  "Himalayan",
  "Japanese Bobtail",
  "Korat",
  "LaPerm",
  "Lykoi",
  "Maine Coon",
  "Manx",
  "Munchkin",
  "Nebelung",
  "Norwegian Forest Cat",
  "Ocicat",
  "Oriental Longhair",
  "Oriental Shorthair",
  "Persian",
  "Pixie-bob",
  "Ragamuffin",
  "Ragdoll",
  "Russian Blue",
  "Savannah",
  "Scottish Fold",
  "Scottish Straight",
  "Selkirk Rex",
  "Siamese",
  "Siberian",
  "Singapura",
  "Snowshoe",
  "Somali",
  "Sphynx",
  "Tonkinese",
  "Toyger",
  "Turkish Angora",
  "Turkish Van",
].sort((a, b) => a.localeCompare(b));
