import { StyleSheet } from "@react-pdf/renderer";

export const workbookPdfStyles = StyleSheet.create({
    body: {
        paddingTop: 50,
        paddingBottom: 65,
        paddingHorizontal: 54,
        fontFamily: "Times-Roman",
        fontSize: 11,
        lineHeight: 1.6,
        color: "#0b2540",
    },
    header: {
        position: "absolute",
        top: 24,
        left: 54,
        right: 54,
        fontSize: 8,
        textAlign: "center",
        color: "#4c6072",
        textTransform: "uppercase",
        fontFamily: "Helvetica-Bold",
    },
    titleBlock: {
        alignItems: "center",
        marginTop: 40,
        marginBottom: 24,
    },
    title: {
        fontSize: 24,
        fontFamily: "Helvetica-Bold",
        textAlign: "center",
        color: "#0b2540",
        textTransform: "uppercase",
        maxWidth: 400,
    },
    hr: {
        borderBottomWidth: 1,
        borderBottomColor: "#0a7dba",
        width: 56,
        marginVertical: 14,
        alignSelf: "center",
    },
    subtitle: {
        fontSize: 12,
        textAlign: "center",
        color: "#4c6072",
        maxWidth: 380,
        lineHeight: 1.5,
    },
    coverMeta: {
        marginTop: 20,
        fontSize: 10,
        textAlign: "center",
        color: "#2cc4b3",
        fontFamily: "Times-Roman",
        fontStyle: "italic",
    },
    h2: {
        fontSize: 14,
        fontFamily: "Helvetica-Bold",
        marginBottom: 10,
        color: "#0b2540",
        textTransform: "uppercase",
    },
    bodyText: {
        fontSize: 11,
        marginBottom: 8,
        textAlign: "justify",
        color: "#0b2540",
    },
    listItem: {
        fontSize: 11,
        marginBottom: 5,
        paddingLeft: 10,
        color: "#0b2540",
    },
    sectionHeading: {
        alignItems: "center",
        marginBottom: 16,
        paddingTop: 8,
    },
    sectionNumber: {
        fontSize: 28,
        fontFamily: "Helvetica-Bold",
        color: "#0a7dba",
        marginBottom: 6,
    },
    sectionRule: {
        borderBottomWidth: 0.5,
        borderBottomColor: "#0a7dba",
        width: 40,
        height: 1,
        marginVertical: 6,
    },
    sectionTitle: {
        fontSize: 13,
        fontFamily: "Times-Roman",
        fontStyle: "italic",
        textAlign: "center",
        color: "#0b2540",
        maxWidth: 360,
        lineHeight: 1.5,
    },
    sectionDescription: {
        fontSize: 10,
        textAlign: "center",
        color: "#4c6072",
        marginTop: 6,
        maxWidth: 400,
    },
    fieldBlock: {
        marginBottom: 14,
    },
    question: {
        fontSize: 11,
        fontFamily: "Times-Roman",
        fontWeight: 700,
        marginBottom: 6,
        color: "#0b2540",
    },
    answer: {
        fontSize: 11,
        marginBottom: 4,
        textAlign: "justify",
        color: "#0b2540",
    },
    line: {
        borderBottomWidth: 1,
        borderBottomColor: "#a9becd",
        height: 18,
        marginBottom: 4,
    },
    footer: {
        position: "absolute",
        bottom: 36,
        left: 54,
        right: 54,
        fontSize: 8,
        textAlign: "center",
        color: "#4c6072",
        borderTopWidth: 0.5,
        borderTopColor: "#e6eef4",
        paddingTop: 8,
    },
    pageNumber: {
        position: "absolute",
        fontSize: 9,
        bottom: 18,
        left: 0,
        right: 0,
        textAlign: "center",
        color: "#999",
    },
});
