import { StyleSheet } from "@react-pdf/renderer";

/** Nice Guy Web Design brand tokens for print PDF (light professional report). */
export const pdfColors = {
    navy: "#0b2540",
    navyDeep: "#071729",
    sky: "#0a7dba",
    skySoft: "#60c4e3",
    teal: "#2cc4b3",
    green: "#2f8f63",
    coral: "#d96558",
    surface: "#f2f6f9",
    card: "#ffffff",
    border: "#d3e0ea",
    muted: "#4c6072",
    body: "#1a2f42",
    white: "#ffffff",
    highBg: "#fde8e4",
    mediumBg: "#fff4df",
    lowBg: "#e8f6ef",
    highText: "#a23b30",
    mediumText: "#8a5a12",
    lowText: "#1f6b45",
};

export const auditPdfStyles = StyleSheet.create({
    page: {
        fontFamily: "Helvetica",
        fontSize: 10,
        color: pdfColors.body,
        backgroundColor: pdfColors.surface,
        paddingTop: 48,
        paddingBottom: 56,
        paddingHorizontal: 40,
    },
    header: {
        position: "absolute",
        top: 18,
        left: 40,
        right: 40,
        fontSize: 8,
        color: pdfColors.muted,
        borderBottomWidth: 1,
        borderBottomColor: pdfColors.border,
        paddingBottom: 6,
    },
    footer: {
        position: "absolute",
        bottom: 22,
        left: 40,
        right: 40,
        fontSize: 8,
        color: pdfColors.muted,
        borderTopWidth: 1,
        borderTopColor: pdfColors.border,
        paddingTop: 6,
        flexDirection: "row",
        justifyContent: "space-between",
    },
    brandMark: {
        fontSize: 11,
        fontFamily: "Helvetica-Bold",
        color: pdfColors.sky,
        letterSpacing: 0.4,
        marginBottom: 18,
    },
    coverTitle: {
        fontSize: 26,
        fontFamily: "Helvetica-Bold",
        color: pdfColors.navy,
        lineHeight: 1.2,
        marginBottom: 10,
    },
    coverSubtitle: {
        fontSize: 12,
        color: pdfColors.muted,
        marginBottom: 22,
    },
    metaRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 10,
        marginBottom: 22,
    },
    metaChip: {
        backgroundColor: pdfColors.card,
        borderWidth: 1,
        borderColor: pdfColors.border,
        borderRadius: 4,
        paddingVertical: 8,
        paddingHorizontal: 10,
        minWidth: "30%",
    },
    metaLabel: {
        fontSize: 8,
        color: pdfColors.muted,
        marginBottom: 3,
        textTransform: "uppercase",
        letterSpacing: 0.6,
    },
    metaValue: {
        fontSize: 11,
        fontFamily: "Helvetica-Bold",
        color: pdfColors.navy,
    },
    scoreBlock: {
        backgroundColor: pdfColors.navy,
        borderRadius: 6,
        padding: 16,
        marginBottom: 20,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    scoreValue: {
        fontSize: 36,
        fontFamily: "Helvetica-Bold",
        color: pdfColors.skySoft,
    },
    scoreLabel: {
        fontSize: 11,
        color: pdfColors.white,
        marginTop: 2,
    },
    scoreCaption: {
        fontSize: 9,
        color: "rgba(255,255,255,0.72)",
        maxWidth: 220,
        textAlign: "right",
    },
    sectionTitle: {
        fontSize: 16,
        fontFamily: "Helvetica-Bold",
        color: pdfColors.navy,
        marginBottom: 8,
    },
    sectionIntro: {
        fontSize: 10,
        color: pdfColors.muted,
        marginBottom: 14,
        lineHeight: 1.45,
    },
    bodyText: {
        fontSize: 10,
        lineHeight: 1.5,
        color: pdfColors.body,
        marginBottom: 10,
    },
    card: {
        backgroundColor: pdfColors.card,
        borderWidth: 1,
        borderColor: pdfColors.border,
        borderRadius: 6,
        padding: 12,
        marginBottom: 10,
    },
    cardTitle: {
        fontSize: 11,
        fontFamily: "Helvetica-Bold",
        color: pdfColors.navy,
        marginBottom: 4,
    },
    cardMeta: {
        fontSize: 8,
        color: pdfColors.muted,
        marginBottom: 6,
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    priorityBadge: {
        fontSize: 8,
        fontFamily: "Helvetica-Bold",
        borderRadius: 3,
        paddingVertical: 3,
        paddingHorizontal: 6,
        alignSelf: "flex-start",
        marginBottom: 6,
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    priorityHigh: {
        backgroundColor: pdfColors.highBg,
        color: pdfColors.highText,
    },
    priorityMedium: {
        backgroundColor: pdfColors.mediumBg,
        color: pdfColors.mediumText,
    },
    priorityLow: {
        backgroundColor: pdfColors.lowBg,
        color: pdfColors.lowText,
    },
    fieldLabel: {
        fontSize: 8,
        fontFamily: "Helvetica-Bold",
        color: pdfColors.sky,
        marginTop: 6,
        marginBottom: 2,
        textTransform: "uppercase",
        letterSpacing: 0.4,
    },
    twoCol: {
        flexDirection: "row",
        gap: 12,
    },
    col: {
        flex: 1,
    },
    screenshotFrame: {
        backgroundColor: pdfColors.card,
        borderWidth: 1,
        borderColor: pdfColors.border,
        borderRadius: 6,
        padding: 8,
        alignItems: "center",
    },
    screenshotCaption: {
        fontSize: 8,
        color: pdfColors.muted,
        marginTop: 6,
        textAlign: "center",
    },
    screenshotMissing: {
        height: 220,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#e8eef3",
        borderRadius: 4,
        width: "100%",
    },
    metricGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8,
    },
    metricCell: {
        width: "30%",
        backgroundColor: pdfColors.card,
        borderWidth: 1,
        borderColor: pdfColors.border,
        borderRadius: 4,
        padding: 8,
    },
    metricLabel: {
        fontSize: 8,
        color: pdfColors.muted,
        marginBottom: 2,
    },
    metricValue: {
        fontSize: 12,
        fontFamily: "Helvetica-Bold",
        color: pdfColors.navy,
    },
    categoryRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingVertical: 6,
        borderBottomWidth: 1,
        borderBottomColor: pdfColors.border,
    },
    mutedNote: {
        fontSize: 9,
        color: pdfColors.muted,
        fontStyle: "italic",
    },
});
