export const RATE_LIMIT_KEY_VERSION = "v1";

export const RATE_LIMIT_ERROR_CODES = {
    EXCEEDED: "RATE_LIMIT_EXCEEDED",
    LOGIN_EXCEEDED: "RATE_LIMIT_LOGIN_EXCEEDED",
    ACTION_EXCEEDED: "RATE_LIMIT_ACTION_EXCEEDED",
    PUBLIC_RESOURCE_EXCEEDED: "RATE_LIMIT_PUBLIC_RESOURCE_EXCEEDED",
    PROVIDER_UNAVAILABLE: "RATE_LIMIT_PROVIDER_UNAVAILABLE",
    CONFIGURATION_ERROR: "RATE_LIMIT_CONFIGURATION_ERROR",
    INVALID_POLICY: "RATE_LIMIT_INVALID_POLICY",
    INVALID_IDENTITY: "RATE_LIMIT_INVALID_IDENTITY",
    BUDGET_EXCEEDED: "RATE_LIMIT_BUDGET_EXCEEDED",
    INTERNAL_ERROR: "RATE_LIMIT_INTERNAL_ERROR",
} as const;
